theme: jekyll-theme-chirpy
baseurl: ''
lang: en-US
timezone: Etc/UTC
title: supershadoe
tagline: dive into my world
description: A website where I post some stuff about software in a slightly detailed form
url: https://supershadoe.me

github:
  username: supershadoe

twitter:
  username: supershadoe

social:
  name: supershadoe
  email: supershadoe5@gmail.com
  links:
    - mailto:supershadoe5@gmail.com
    - https://twitter.com/supershadoe
    - https://github.com/supershadoe
avatar: https://avatars.githubusercontent.com/u/53053643
toc: true
comments:
  active:

paginate: 10

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "my_bio_repo"
  - Gemfile
  - Gemfile.lock

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
